### ISSUE TITLE
[Bug Report] Downloads don't complete

### ISSUE THREAD

**Issue by MagosCawl** [HanaDigital/NovelScraper#60] opened 2021-09-11 12:34 UTC
**Please complete the following information):**
 - Operating System [OS]: Windows 10 20H2
 - 32bit / 64bit: 64-bit
 - App Version: 2.0.5

**Describe the bug**
After downloading novels from novelfull.com, the novel is not moved into "Downloaded" section of app. When I check in Downloads\NovelScraper-Library\ I can see that the data has been stored in a .json format but no .epub was created.

**To Reproduce**
1. Try to download https://novelfull.com/split-zone-no13.html or https://novelfull.com/the-immortals-poison.html (same for all though)
2. It will not move to "Downloaded" and data is only stored in .json and not .epub
3. Refreshing the novel shows that all data was successfully downloaded

**Expected behavior**
For it to generate an .epub file - unless this feature is no longer supported?

**Screenshots**
https://imgur.com/a/zRctRHZ (was unable to upload image here)

**Comment by webdagger** [comment] 2021-09-13 10:40
I will pick this issue up and investigate.

**Comment by jiskim** [comment] 2021-10-04 22:59
the issue seems to be that when searching with an url, the genre and summary are not defaulted, in some cases like your example the genre is not  found by the parser and default to "". there is no logic checking before the epub creation if the genre is not  empty or null.

#63 

i did a pul lrequest  doing a quick fix on  the cause of it crashing

**Comment by dr-nyt** [comment] 2021-10-05 06:14
This issue has been up for way too long, all hail @webdagger and @jiskim, a fix should be up soon.

**Comment by dr-nyt** [comment] 2021-12-21 10:01
This is fixed as far as I remember. Closing.

**Closed by dr-nyt** 2021-12-21 10:01 UTC
Labels: bug
